# Generated by Django 4.2.2 on 2023-12-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
