# Generated by Django 4.2.2 on 2023-12-14 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newscomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 14, 14, 57, 34, 478646)),
        ),
    ]
